// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// 1. Usamos los nombres estándar que tienes en tu .env
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// 2. Validación de seguridad (opcional pero recomendada)
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.error("⚠️ Faltan las credenciales de Supabase en el archivo .env");
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});